### ISSUE TITLE
social4git sync: malformed unpack status: 0024unpack index-pack abnormal exit

### ISSUE THREAD

**Issue by petar** [social4git/social4git#5]
Running `social4git sync` occasionally (!) produces an error:
```
malformed unpack status: 0024unpack index-pack abnormal exit
```
This is flaky behavior. Rerunning sync a few times tends to fix the problem.
The error comes from the github servers.

It is currently unclear whether this issue is due to:
- a bug in go-git (the git client library we use)
- a non-standard corner-case behavior on the github git servers

**Comment by tlc28** [comment]
Hi @petar 
First of all, I wanted to thank you for sharing `social4git`. I like the idea a lot! I can't wait to see what happens next!

As far as this issue is concerned, I can reproduce the problem, with a small difference in the error message: `unpack error: unpack-objects abnormal exit`. But, I guess, the two are the same.

**Comment by petar** [comment]
Thank you @tlc28. I tried hosting my profile on GitLab and got the same message as you `unpack error: unpack-objects abnormal exit`. This suggests that the bug is either in go-git or somehow in the way social4git uses go-git.

**Comment by petar** [comment]
I added a debug mode whereby social4git operates on repositories on disk (rather than in memory). This let me get ahold of the repo before it is being pushed back to the origin (github in my case). Then I was able to push manually to see what goes wrong. I got: `remote: error: object 02b1a2731b0d3db1103db41dcc0de3d0558ebf5a: treeNotSorted: not properly sorted`
